# Generated by Django 4.2.4 on 2023-08-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_place_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Hotel',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='hotel',
        ),
    ]
