# Generated by Django 4.2.4 on 2023-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_category_hotel_rename_category_place_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.CharField(default=0, max_length=255, verbose_name='Цена'),
        ),
    ]
