# Generated by Django 4.2.4 on 2023-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_place_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
        migrations.AddField(
            model_name='place',
            name='geolocation',
            field=models.CharField(default=0, max_length=255, verbose_name='Геолокация'),
        ),
    ]
