# Generated by Django 4.2.4 on 2023-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_geo_place_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='cards', verbose_name='Карточки')),
                ('price', models.CharField(default=0, max_length=255, verbose_name='Цена')),
            ],
        ),
    ]
