# Generated by Django 4.2.4 on 2023-09-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chill_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.AddField(
            model_name='chill',
            name='chill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chill_type'),
        ),
        migrations.AddField(
            model_name='chill',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.price_type'),
        ),
    ]
