# Generated by Django 4.2.4 on 2023-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chill_type_price_type_chill_chill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chill',
            name='img',
            field=models.ImageField(blank=True, upload_to='cards', verbose_name='Карточки'),
        ),
    ]
