# Generated by Django 4.2.4 on 2023-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_chill_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
