# Generated by Django 4.2.4 on 2024-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_date_type_event_type_geo_type_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='date_type',
        ),
        migrations.AddField(
            model_name='events',
            name='dateEvent',
            field=models.CharField(default=0, max_length=255, verbose_name='Дата'),
        ),
    ]
