# Generated by Django 4.2.4 on 2024-03-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_mymodel_remove_events_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
