# Generated by Django 4.2.4 on 2024-03-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='typeE',
            field=models.CharField(default=0, max_length=255, verbose_name='Название'),
        ),
    ]
