# Generated by Django 4.2.4 on 2024-03-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event_typee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='BeachType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='cards', verbose_name='Карточки')),
                ('isAllowedIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Купание запрещено')),
                ('lenght', models.CharField(default=0, max_length=255, verbose_name='Название')),
                ('width', models.CharField(default=0, max_length=255, verbose_name='Название')),
                ('sunloungersIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Шезлонги')),
                ('coctelIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Коктель')),
                ('showerIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Душ')),
                ('sportIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Спорт')),
                ('gymIMG', models.ImageField(blank=True, upload_to='cards', verbose_name='Gym')),
                ('beach_geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beachtype')),
                ('beach_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beachgeo')),
            ],
        ),
    ]
