# Generated by Django 4.2.4 on 2024-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_beachgeo_beachtype_beach'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='geolocation',
            field=models.CharField(default=0, max_length=255, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='beach',
            name='lenght',
            field=models.CharField(default=0, max_length=255, verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='beach',
            name='width',
            field=models.CharField(default=0, max_length=255, verbose_name='Ширина'),
        ),
    ]
