# Generated by Django 4.2.4 on 2024-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_beach_geolocation_alter_beach_lenght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='geolocation',
            field=models.CharField(default=0, max_length=255, verbose_name='Геолокация'),
        ),
    ]
