# Generated by Django 4.2.4 on 2024-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_beach_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.AddField(
            model_name='beach',
            name='beach_type_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beachcost'),
        ),
    ]
