# Generated by Django 5.0.3 on 2024-03-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_typegeorest_typekitchen_typesrests_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='TypeGeoRest',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opentill',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='type_of_kitchen',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.CharField(default=0, max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=0, max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(default=0, max_length=255, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='RatingType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ratingtype'),
        ),
    ]
