# Generated by Django 5.0.3 on 2024-03-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_ratingtype_remove_restaurant_typegeorest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='link',
        ),
    ]
